services:
  - type: web
    name: discord-server-site
    env: node
    branch: main
    repo: https://github.com/Atomicszsa/Vorhrox_Realm
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_VERSION
        value: 9
