services:
  - type: web
    name: discord-server-site
    env: node
    plan: free
    branch: main
    repo: <https://github.com/Atomicszsa/Vorhrox_Realm/> # Replace with your GitHub/GitLab/Bitbucket repository URL
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
